# Generated by Django 4.1.4 on 2022-12-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At: '),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At: '),
        ),
    ]
